//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Activities struct {
	ID             string `sql:"primary_key"`
	CreatedAt      *time.Time
	UpdatedAt      *time.Time
	DeletedAt      *time.Time
	ActivityTypeID string
	TableName      string
	TableID        string
	UserID         string
}
