//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Companies struct {
	ID             string `sql:"primary_key"`
	CreatedAt      *time.Time
	UpdatedAt      *time.Time
	DeletedAt      *time.Time
	Name           string
	OrganizationID *string
	Slug           string
	IsMain         *string
	Email          *string
}
