//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Users struct {
	ID             string `sql:"primary_key"`
	CreatedAt      *time.Time
	UpdatedAt      *time.Time
	DeletedAt      *time.Time
	Name           *string
	Username       *string
	Email          *string
	Password       *string
	IsSuperAdmin   *bool
	ActivatedAt    *time.Time
	LanguageID     *string
	OrganizationID *string
	RoleID         *string
	StatusID       *string
}
