//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Modules = newModulesTable("membership", "modules", "")

type modulesTable struct {
	mysql.Table

	// Columns
	ID        mysql.ColumnString
	CreatedAt mysql.ColumnTimestamp
	UpdatedAt mysql.ColumnTimestamp
	DeletedAt mysql.ColumnTimestamp
	Name      mysql.ColumnString
	Path      mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type ModulesTable struct {
	modulesTable

	NEW modulesTable
}

// AS creates new ModulesTable with assigned alias
func (a ModulesTable) AS(alias string) *ModulesTable {
	return newModulesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ModulesTable with assigned schema name
func (a ModulesTable) FromSchema(schemaName string) *ModulesTable {
	return newModulesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ModulesTable with assigned table prefix
func (a ModulesTable) WithPrefix(prefix string) *ModulesTable {
	return newModulesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ModulesTable with assigned table suffix
func (a ModulesTable) WithSuffix(suffix string) *ModulesTable {
	return newModulesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newModulesTable(schemaName, tableName, alias string) *ModulesTable {
	return &ModulesTable{
		modulesTable: newModulesTableImpl(schemaName, tableName, alias),
		NEW:          newModulesTableImpl("", "new", ""),
	}
}

func newModulesTableImpl(schemaName, tableName, alias string) modulesTable {
	var (
		IDColumn        = mysql.StringColumn("id")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		UpdatedAtColumn = mysql.TimestampColumn("updated_at")
		DeletedAtColumn = mysql.TimestampColumn("deleted_at")
		NameColumn      = mysql.StringColumn("name")
		PathColumn      = mysql.StringColumn("path")
		allColumns      = mysql.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, NameColumn, PathColumn}
		mutableColumns  = mysql.ColumnList{CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, NameColumn, PathColumn}
	)

	return modulesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,
		DeletedAt: DeletedAtColumn,
		Name:      NameColumn,
		Path:      PathColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
