//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Organizations = newOrganizationsTable("membership", "organizations", "")

type organizationsTable struct {
	mysql.Table

	// Columns
	ID        mysql.ColumnString
	CreatedAt mysql.ColumnTimestamp
	UpdatedAt mysql.ColumnTimestamp
	DeletedAt mysql.ColumnTimestamp
	Name      mysql.ColumnString
	Email     mysql.ColumnString
	Slug      mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type OrganizationsTable struct {
	organizationsTable

	NEW organizationsTable
}

// AS creates new OrganizationsTable with assigned alias
func (a OrganizationsTable) AS(alias string) *OrganizationsTable {
	return newOrganizationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OrganizationsTable with assigned schema name
func (a OrganizationsTable) FromSchema(schemaName string) *OrganizationsTable {
	return newOrganizationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OrganizationsTable with assigned table prefix
func (a OrganizationsTable) WithPrefix(prefix string) *OrganizationsTable {
	return newOrganizationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OrganizationsTable with assigned table suffix
func (a OrganizationsTable) WithSuffix(suffix string) *OrganizationsTable {
	return newOrganizationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOrganizationsTable(schemaName, tableName, alias string) *OrganizationsTable {
	return &OrganizationsTable{
		organizationsTable: newOrganizationsTableImpl(schemaName, tableName, alias),
		NEW:                newOrganizationsTableImpl("", "new", ""),
	}
}

func newOrganizationsTableImpl(schemaName, tableName, alias string) organizationsTable {
	var (
		IDColumn        = mysql.StringColumn("id")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		UpdatedAtColumn = mysql.TimestampColumn("updated_at")
		DeletedAtColumn = mysql.TimestampColumn("deleted_at")
		NameColumn      = mysql.StringColumn("name")
		EmailColumn     = mysql.StringColumn("email")
		SlugColumn      = mysql.StringColumn("slug")
		allColumns      = mysql.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, NameColumn, EmailColumn, SlugColumn}
		mutableColumns  = mysql.ColumnList{CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, NameColumn, EmailColumn, SlugColumn}
	)

	return organizationsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,
		DeletedAt: DeletedAtColumn,
		Name:      NameColumn,
		Email:     EmailColumn,
		Slug:      SlugColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
