//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Roles = newRolesTable("membership", "roles", "")

type rolesTable struct {
	mysql.Table

	// Columns
	ID        mysql.ColumnString
	CreatedAt mysql.ColumnTimestamp
	UpdatedAt mysql.ColumnTimestamp
	DeletedAt mysql.ColumnTimestamp
	Name      mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type RolesTable struct {
	rolesTable

	NEW rolesTable
}

// AS creates new RolesTable with assigned alias
func (a RolesTable) AS(alias string) *RolesTable {
	return newRolesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RolesTable with assigned schema name
func (a RolesTable) FromSchema(schemaName string) *RolesTable {
	return newRolesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RolesTable with assigned table prefix
func (a RolesTable) WithPrefix(prefix string) *RolesTable {
	return newRolesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RolesTable with assigned table suffix
func (a RolesTable) WithSuffix(suffix string) *RolesTable {
	return newRolesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRolesTable(schemaName, tableName, alias string) *RolesTable {
	return &RolesTable{
		rolesTable: newRolesTableImpl(schemaName, tableName, alias),
		NEW:        newRolesTableImpl("", "new", ""),
	}
}

func newRolesTableImpl(schemaName, tableName, alias string) rolesTable {
	var (
		IDColumn        = mysql.StringColumn("id")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		UpdatedAtColumn = mysql.TimestampColumn("updated_at")
		DeletedAtColumn = mysql.TimestampColumn("deleted_at")
		NameColumn      = mysql.StringColumn("name")
		allColumns      = mysql.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, NameColumn}
		mutableColumns  = mysql.ColumnList{CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, NameColumn}
	)

	return rolesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,
		DeletedAt: DeletedAtColumn,
		Name:      NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
