//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Activities = Activities.FromSchema(schema)
	ActivityTypes = ActivityTypes.FromSchema(schema)
	BookmarkTypes = BookmarkTypes.FromSchema(schema)
	Bookmarks = Bookmarks.FromSchema(schema)
	Companies = Companies.FromSchema(schema)
	CompanyEmailDomains = CompanyEmailDomains.FromSchema(schema)
	CompanyUsers = CompanyUsers.FromSchema(schema)
	GooseDbVersion = GooseDbVersion.FromSchema(schema)
	Groups = Groups.FromSchema(schema)
	Languages = Languages.FromSchema(schema)
	Modules = Modules.FromSchema(schema)
	Organizations = Organizations.FromSchema(schema)
	Privileges = Privileges.FromSchema(schema)
	RoleGroups = RoleGroups.FromSchema(schema)
	RolePrivileges = RolePrivileges.FromSchema(schema)
	Roles = Roles.FromSchema(schema)
	Sessions = Sessions.FromSchema(schema)
	Statuses = Statuses.FromSchema(schema)
	UserGroups = UserGroups.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
